coverage:
  status:
    project:
      default:
        informational: true
      web:
        flags:
          - web
        paths:
          - "apps/web/"
        informational: true
      strapi:
        flags:
          - strapi
        paths:
          - "apps/strapi/"
        informational: true

    patch:
      default:
        informational: true

flags:
  web:
    paths:
      - apps/web/
    carryforward: true
  strapi:
    paths:
      - apps/strapi/
    carryforward: true

ignore:
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/dist/**"
  - "**/.tmp/**"
  - "**/.cache/**"
  - "**/coverage/**"
  - "**/*.config.*"
  - "**/test/**"
  - "**/tests/**" 